### ISSUE TITLE
Warnings from ying.py

### ISSUE THREAD

**Issue by minjiacheng** [AndyHuang1995/Image-Contrast-Enhancement#1]
When running ying.py I get the following warnings:
RuntimeWarning: invalid value encountered in power
  I = (I[:,:,0]*I[:,:,1]*I[:,:,2])**(1/3)
RuntimeWarning: invalid value encountered in greater
  tmp[tmp > 255] = 255
RuntimeWarning: invalid value encountered in less
  tmp[tmp<0] = 0

Doesn't seem to stop code from executing but i wonder what those warnings mean.

**Comment by AndyHuang1995** [comment]
Hi,
Please refer to the link below.
https://stackoverflow.com/questions/45384602/numpy-runtimewarning-invalid-value-encountered-in-power?rq=1
