### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'imresize'

### ISSUE THREAD

**Issue by denddyprod** [AndyHuang1995/Image-Contrast-Enhancement#12]
I tried to use ying.py but I receive an error. 

> AttributeError: module 'scipy.misc' has no attribute 'imresize'

It's about imresize, because

> imresize is deprecated! imresize is deprecated in SciPy 1.0.0, and will be removed in 1.3.0. Use Pillow instead: numpy.array(Image.fromarray(arr).resize()).

**Comment by MrGroot97** [comment]
it's better to install python modules with same version  as in requirements.txt or install scipy 1.2.2 with support python version as scipy 1.2.2 not supported python 3.7 or higher
